#!/bin/bash
self=`basename "$0"`

declare -a inputs

input_index=0

while read line; do
  echo "$line"
  inputs[input_index]=$line
  input_index=$((input_index + 1))
done


if [ -z "$COMMANDS" ]; then
  COMMANDS=""
fi
read -e -p $'\e[32m>>\e[0m ' response </dev/tty
if [ ! -z "${response}" ]; then
  if [ "${response}" = 'done' ]; then
    echo $COMMANDS
  else
    COMMANDS="$COMMANDS | $response"
    printf '%s\n' "${inputs[@]}" | eval "$response" | COMMANDS=$COMMANDS $self
  fi
fi
