#!/bin/bash
self=`basename "$0"`

declare -a inputs

inputs=`$1`
printf '%s\n' "${inputs[@]}"
COMMANDS="$1"
COMMAND=""
while true
do
  read -e -p $'\e[32m>>\e[0m ' response </dev/tty
  if [ ! -z "${response}" ]; then
    if [ "${response}" = 'done' ]; then
      echo $COMMANDS
      break
    else
      if [ "${response}" = 'step' ]; then
        COMMANDS="$COMMANDS | $COMMAND"
        COMMAND=""
        inputs=$(printf '%s\n' "${inputs[@]}" | eval "$COMMANDS")
        printf '%s\n' "${inputs[@]}"
      else
        COMMAND=$response
        printf '%s\n' "${inputs[@]}" | eval "$COMMAND"
      fi
    fi
  fi
done
